GET http://localhost:5056/games

###
GET http://localhost:5056/games/3

###
POST http://localhost:5056/games
Content-Type: application/json

{

  "name": "TEST GAME",
  "genreId": 1,
  "price": 9.99,
  "releaseDate": "2026-03-03"
}

###
PUT http://localhost:5056/games/2
Content-Type: application/json

{
  "name": "Street Fighter 6 Turbo",
  "genreId": 1,
  "price": 19.99,
  "releaseDate": "2026-03-03"
}

###
DELETE http://localhost:5056/games/3

###
GET http://localhost:5056/genres